/* Entrega e custo de transporte são registros distintos do valor da compra. */
function dataEntregaLocal(em) {
  if (!em) return '';
  if (/^\d{4}-\d{2}-\d{2}$/.test(String(em||''))) return em;
  const d=new Date(em);if(!Number.isFinite(d.getTime()))return '';
  return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
}
function chaveFrete(ocId,recebimentoId){return 'rec-'+encodeURIComponent(ocId)+'|'+encodeURIComponent(recebimentoId);}
function recebimentosTransporte(ocs=lista('oc')){
  return ocs.flatMap(o=>(o.recebimentos||[]).filter(r=>r.id).map(r=>({id:chaveFrete(o.id,r.id),ocId:o.id,recebimentoId:r.id,codigo:o.codigo,transportadoraId:r.transportadoraId||'',dataEntrega:dataEntregaLocal(r.em),fornecedorId:o.fornecedorId,fornecedor:(o.fornecedor||{}).nome,origem:(o.fornecedor||{}).nome||'',destino:o.obra||'',conteudo:(r.itens||[]).map(i=>fmt.numero(i.qtd)+' '+(i.unid||'')+' '+(i.descricao||(o.itens||[]).find(x=>x.id===i.itemId)?.descricao||'Material')).join('; '),valor:null,custeio:'a_definir'})));
}
function movimentosTransporte(ocs=lista('oc'),fretes=lista('frete')){
  const base=new Map(recebimentosTransporte(ocs).map(r=>[r.id,r]));
  for(const f of fretes){
    if(f.ativo===false||f.apagadoEm)continue;
    if(f.ocId&&f.recebimentoId){const k=chaveFrete(f.ocId,f.recebimentoId),r=base.get(k);if(r)base.set(k,{...r,...f,id:k,dataEntrega:r.dataEntrega,conteudo:r.conteudo,codigo:r.codigo});}
    else if(!f.ocId&&!f.recebimentoId)base.set(f.id,{...f});
  }
  return [...base.values()].sort((a,b)=>String(b.dataEntrega).localeCompare(String(a.dataEntrega)));
}
function resumoFretes(movs){return movs.reduce((s,r)=>{s.entregas++;if(r.custeio==='incluso'||r.custeio==='terceiro')s.semCobranca++;else if(r.custeio==='empresa'&&typeof r.valor==='number'&&Number.isFinite(r.valor)&&r.valor>=0)s.gasto+=r.valor;else s.pendentes++;return s;},{entregas:0,gasto:0,pendentes:0,semCobranca:0});}
let mesTransportes='';
function htmlResumoFretes(r){return '<div class="rede-indicadores"><div class="cartao"><span>Entregas no mês</span><strong>'+r.entregas+'</strong></div><div class="cartao"><span>Gasto registrado</span><strong>'+fmt.brl(r.gasto)+'</strong><small>Frete cobrado da Impresilk</small></div><div class="cartao"><span>A conferir</span><strong>'+r.pendentes+'</strong><small>Valor ou responsável não informado</small></div><div class="cartao"><span>Sem cobrança separada</span><strong>'+r.semCobranca+'</strong><small>Incluso na compra ou pago por terceiro</small></div></div>';}
function editarTransportadora(id){
  const t=achar('transp',id)||{};
  abrirModal({titulo:id?'Editar transportadora':'Nova transportadora',largo:true,corpo:'<div id="redeForm"><div class="linha">'+campo('Nome',entrada('nome',t.nome))+campo('CNPJ',entrada('cnpj',t.cnpj))+'</div><div class="linha">'+campo('Contato',entrada('contato',t.contato))+campo('Telefone',entrada('telefone',t.telefone,{tipo:'tel'}))+'</div>'+campo('Regiões atendidas',areaTexto('regioes',t.regioes,'Estados, cidades e áreas atendidas'))+campo('Rotas / origem e destino',areaTexto('rotas',t.rotas,'Ex.: São Paulo → Belo Horizonte; coleta em fornecedores…'))+campo('O que transporta para a Impresilk',areaTexto('cargas',t.cargas,'Ex.: chapas, perfis longos, bobinas…'))+'<div class="linha">'+campo('Prazo habitual',entrada('prazo',t.prazo,{placeholder:'Ex.: 2 a 3 dias úteis'}))+campo('Frequência de coleta',entrada('frequencia',t.frequencia))+'</div>'+campo('Cuidados, limites e características',areaTexto('caracteristicas',t.caracteristicas,'Comprimento máximo, carga frágil, agendamento, seguro…'))+campo('Situação',seletor('situacao',t.ativo===false?'inativo':'ativo',[{v:'ativo',t:'Ativa'},{v:'inativo',t:'Arquivada — mantém entregas e gastos'}]))+'</div>',acoes:[{texto:'Cancelar',aoClicar:f=>fecharEste(f)},{texto:'Salvar transportadora',classe:'primario',aoClicar:f=>{const d=lerCampos(f.querySelector('#redeForm'));if(!d.nome.trim()){toast('Informe o nome da transportadora.','ruim');return;}const cnpj=d.cnpj.replace(/\D/g,'');if(cnpj&&lista('transp').some(x=>x.id!==id&&String(x.cnpj||'').replace(/\D/g,'')===cnpj)){toast('Este CNPJ já tem um cadastro.','ruim');return;}salvar('transp',{...t,...d,nome:d.nome.trim(),ativo:d.situacao==='ativo'});fecharEste(f);render();}}]});
}
function editarFrete(id,transportadoraId){
  const mov=movimentosTransporte().find(x=>x.id===id)||{},ant=achar('frete',id)||{};
  const recs=recebimentosTransporte();
  const ts=opcoesRede('transp');const tid=mov.transportadoraId||transportadoraId;if(tid&&!ts.some(x=>x.v===tid)){const t=achar('transp',tid);if(t)ts.push({v:tid,t:t.nome+' (arquivada)'});}
  const fundo=abrirModal({titulo:id?'Conferir entrega e frete':'Registrar entrega / frete',largo:true,corpo:'<div id="redeForm">'+campo('Transportadora',seletor('transportadoraId',tid,ts,'Escolha a transportadora'))+campo('Vincular a um recebimento',seletor('recebimento',mov.recebimentoId?mov.id:'',recs.filter(r=>!achar('frete',r.id)||r.id===id).map(r=>({v:r.id,t:(r.codigo||'OC')+' · '+fmt.data(r.dataEntrega)+' · '+r.conteudo.slice(0,90)})),'Entrega avulsa — sem recebimento vinculado'))+ '<div class="linha">'+campo('Data da entrega',entrada('dataEntrega',mov.dataEntrega||hojeISO(),{tipo:'date'}))+campo('Fornecedor (opcional)',seletor('fornecedorId',mov.fornecedorId,opcoesRede('forn'),'Não informado'))+'</div><div class="linha">'+campo('Origem / coleta',entrada('origem',mov.origem))+campo('Destino',entrada('destino',mov.destino))+'</div>'+campo('O que trouxe',areaTexto('conteudo',mov.conteudo))+'<div class="linha">'+campo('Responsável pelo frete',seletor('custeio',mov.custeio||'a_definir',[{v:'a_definir',t:'Ainda não informado'},{v:'empresa',t:'Cobrado da Impresilk'},{v:'incluso',t:'Incluso no valor da compra'},{v:'terceiro',t:'Pago por terceiro'}]))+campo('Valor do frete (R$)',entrada('valor',mov.valor==null?'':paraCampo(mov.valor),{inputmode:'decimal',placeholder:'Em branco = não informado'}))+'</div>'+campo('Documento / CT-e (opcional)',entrada('documento',mov.documento))+campo('Observações',areaTexto('obs',mov.obs))+'</div><p class="legenda">A entrega vinculada usa a data e os itens do recebimento. Este controle não altera o total da ordem de compra nem confirma pagamento.</p>',acoes:[{texto:'Cancelar',aoClicar:f=>fecharEste(f)},{texto:'Salvar registro',classe:'primario',aoClicar:f=>{
    const d=lerCampos(f.querySelector('#redeForm')),rec=recs.find(r=>r.id===d.recebimento);
    if(!d.transportadoraId||(!rec&&(!d.dataEntrega||diasAte(d.dataEntrega)==null||!d.conteudo.trim()))){toast('Informe transportadora, data válida e o que foi entregue.','ruim');return;}
    if(mov.recebimentoId&&d.recebimento!==mov.id){toast('Este registro já está vinculado. Edite os dados sem trocar o recebimento.','ruim');return;}
    if(id&&!mov.recebimentoId&&rec){toast('Um registro avulso deve continuar avulso. Edite o recebimento separadamente.','ruim');return;}
    const texto=String(d.valor).trim(),valor=texto?numeroBR(texto):null;
    if(texto&&(!/^-?\d[\d.,\s]*$/.test(texto)||!Number.isFinite(valor)||valor<0)){toast('Informe um valor válido, sem sinal negativo.','ruim');return;}
    if(rec&&achar('frete',rec.id)&&rec.id!==id){toast('Este recebimento já tem um frete. Abra o registro existente.','ruim');return;}
    salvar('frete',{...ant,...d,id:rec?rec.id:(id||undefined),ocId:rec?rec.ocId:'',recebimentoId:rec?rec.recebimentoId:'',dataEntrega:rec?rec.dataEntrega:d.dataEntrega,conteudo:rec?rec.conteudo:d.conteudo,valor:d.custeio==='empresa'?valor:null,ativo:true});fecharEste(f);render();
  }}]});
  const raiz=fundo.querySelector('#redeForm'),sel=raiz.querySelector('[data-campo="recebimento"]');
  if(id)sel.disabled=true;
  function aplicarRec(preencher=false){const r=recs.find(x=>x.id===sel.value);for(const k of ['dataEntrega','conteudo']){const i=raiz.querySelector('[data-campo="'+k+'"]');i.readOnly=!!r;if(r)i.value=r[k];}if(r&&preencher)for(const k of ['origem','destino','fornecedorId'])raiz.querySelector('[data-campo="'+k+'"]').value=r[k]||'';}
  sel.onchange=()=>aplicarRec(true);aplicarRec();
  const pag=raiz.querySelector('[data-campo="custeio"]'),val=raiz.querySelector('[data-campo="valor"]');function atualizarValor(){val.disabled=pag.value!=='empresa';}pag.onchange=atualizarValor;atualizarValor();
}
TELAS.transportadoras=function(el,args){
  const t=args[0]?achar('transp',args[0]):null,mes=mesTransportes||hojeISO().slice(0,7),todos=movimentosTransporte(),movs=todos.filter(r=>r.dataEntrega.slice(0,7)===mes&&(!t||r.transportadoraId===t.id));
  cabecalho(t?t.nome:'Transportadoras',t?'Cobertura, cargas e entregas desta transportadora.':'Saiba quem atende cada região e acompanhe o transporte das suas compras.',t?'<a class="btn" href="#/transportadoras">← Transportadoras</a><button class="btn" id="editarTransp">Editar cadastro</button><button class="btn primario" id="novoFrete">+ Registrar entrega</button>':'<button class="btn" id="novoFrete">+ Registrar entrega</button><button class="btn primario" id="novaTransp">+ Nova transportadora</button>');
  el.innerHTML=navRede('transportadoras')+(t?'<section class="cartao"><div class="rede-titulo"><div><span class="rede-kicker">🚚 Cobertura e operação</span><h2>'+esc(t.nome)+'</h2></div><span class="etiqueta">'+(t.ativo===false?'Arquivada':'Ativa')+'</span></div><div class="rede-cobertura">'+[['📍 Regiões atendidas',t.regioes],['↔ Rotas',t.rotas],['📦 O que transporta',t.cargas],['⏱ Prazo e frequência',[t.prazo,t.frequencia].filter(Boolean).join(' · ')],['☎ Contato',[t.contato,t.telefone].filter(Boolean).join(' · ')],['ℹ Características',t.caracteristicas]].map(([a,b])=>'<div><h3>'+a+'</h3><p>'+esc(b||'Ainda não informado')+'</p></div>').join('')+'</div></section>':'')+'<div class="rede-titulo"><h2>Entregas e custos</h2>'+campo('Mês de entrega','<input id="mesTransportes" type="month" value="'+esc(mes)+'">')+'</div>'+htmlResumoFretes(resumoFretes(movs))+'<p class="legenda">O gasto considera apenas valores registrados. Recebimentos sem custo definido aparecem em “A conferir”; não são tratados como frete grátis.</p>';
  if(!t){const ts=lista('transp').sort((a,b)=>String(a.nome).localeCompare(String(b.nome),'pt-BR'));el.innerHTML+='<div class="rede-pesquisa">'+campo('Buscar por nome, região, rota ou tipo de carga','<input id="buscaRede" type="search" placeholder="Ex.: São Paulo, bobinas, chapas…">')+'</div><div class="rede-grid">'+ts.map(x=>{const r=resumoFretes(movs.filter(m=>m.transportadoraId===x.id));return '<a class="cartao rede-card" data-rede-texto="'+esc([x.nome,x.regioes,x.rotas,x.cargas].join(' '))+'" href="#/transportadoras/'+esc(x.id)+'"><span class="rede-kicker">🚚 '+(x.ativo===false?'Arquivada':'Transportadora')+'</span><h3>'+esc(x.nome)+'</h3><p><b>Atende:</b> '+esc(x.regioes||'Regiões não informadas')+'</p><p><b>Transporta:</b> '+esc(x.cargas||'Cargas não informadas')+'</p><div class="rede-meta"><span>'+r.entregas+' entregas</span><span>'+fmt.brl(r.gasto)+'</span><span>'+r.pendentes+' a conferir</span></div><span class="rede-ver">Ver rotas e histórico →</span></a>';}).join('')+'</div><p id="redeSemBusca" class="legenda" hidden>Nenhuma transportadora encontrada.</p>'+(!ts.length?vazio('🚚','Cadastre a primeira transportadora','Informe as regiões, os tipos de carga e o contato. Depois vincule as entregas.'):'');const sem=movs.filter(r=>!r.transportadoraId);if(sem.length)el.innerHTML+='<div class="aviso atencao">'+sem.length+' recebimento(s) neste mês sem transportadora. Abra a entrega na lista abaixo para vincular.</div>';}
  el.innerHTML+='<section class="cartao"><h3>📦 O que chegou em '+esc(mes.split('-').reverse().join('/'))+'</h3>'+(movs.length?'<div class="tabela-rolagem"><table><thead><tr><th>Data / compra</th><th>Transportadora / trajeto</th><th>O que trouxe</th><th>Frete registrado</th><th></th></tr></thead><tbody>'+movs.map(r=>'<tr><td>'+fmt.data(r.dataEntrega)+(r.ocId?'<br><a href="#/compras/'+esc(r.ocId)+'">'+esc(r.codigo||'Ver compra')+'</a>':'<br>Entrega avulsa')+'</td><td><b>'+esc((achar('transp',r.transportadoraId)||{}).nome||'Não vinculada')+'</b><div class="legenda">'+esc(r.origem||'Origem não informada')+' → '+esc(r.destino||'Destino não informado')+'</div></td><td class="rede-conteudo">'+esc(r.conteudo)+'</td><td>'+(r.custeio==='empresa'&&r.valor!=null?fmt.brl(r.valor):r.custeio==='incluso'?'Incluso na compra':r.custeio==='terceiro'?'Pago por terceiro':'A conferir')+(r.documento?'<div class="legenda">'+esc(r.documento)+'</div>':'')+'</td><td><button class="btn pequeno" data-frete="'+esc(r.id)+'">Conferir</button></td></tr>').join('')+'</tbody></table></div>':'<p class="legenda">Nenhuma entrega registrada neste mês.</p>')+'</section>';
  document.getElementById('mesTransportes').onchange=e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){mesTransportes=e.target.value;render();}};document.getElementById('novoFrete').onclick=()=>editarFrete(null,t?.id);const n=document.getElementById('novaTransp');if(n)n.onclick=()=>editarTransportadora(null);const ed=document.getElementById('editarTransp');if(ed)ed.onclick=()=>editarTransportadora(t.id);el.querySelectorAll('[data-frete]').forEach(b=>b.onclick=()=>editarFrete(b.dataset.frete,t?.id));ligarBuscaRede(el);
};
