/* Entrega e custo de transporte são registros distintos do valor da compra. */
function dataEntregaLocal(em) {
  if (!em) return '';
  if (/^\d{4}-\d{2}-\d{2}$/.test(String(em||''))) return dataFreteValida(em)?em:'';
  const d=new Date(em);if(!Number.isFinite(d.getTime()))return '';
  return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);
}
function dataFreteValida(s){return typeof s==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(new Date(s+'T12:00:00Z').getTime())&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s;}
const UFS_TRANSPORTE='AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ');
const CARGAS_TRANSPORTE=['Chapas de ACM','Chapas plásticas / acrílico','Bobinas / lonas / adesivos','Perfis e peças longas','MDF / madeira','Iluminação / eletrônicos','Ferragens / acessórios','Produtos acabados'];
function custoFretePendente(r){return !['incluso','terceiro'].includes(r.custeio)&&!(r.custeio==='empresa'&&typeof r.valor==='number'&&Number.isFinite(r.valor)&&r.valor>=0);}
function inteligenciaFretes(movs){
  const pagos=movs.filter(r=>!custoFretePendente(r)&&r.custeio==='empresa'),mensurados=movs.filter(r=>dataFreteValida(r.dataPrevista)&&dataFreteValida(r.dataEntrega));
  const atrasados=mensurados.filter(r=>r.dataEntrega>r.dataPrevista);
  return {mensurados:mensurados.length,noPrazo:mensurados.length-atrasados.length,atrasados:atrasados.length,media:pagos.length?pagos.reduce((s,r)=>s+r.valor,0)/pagos.length:null,custos:pagos.length,ocorrencias:movs.filter(r=>r.ocorrencia&&r.ocorrencia!=='nenhuma'&&r.ocorrenciaStatus!=='resolvida').length};
}
function pendenciasCadastroTransporte(t){return [!String(t.telefone||'').trim()&&'contato',!(t.ufs||[]).length&&!String(t.regioes||'').trim()&&'cobertura',!(t.tiposCarga||[]).length&&!String(t.cargas||'').trim()&&'tipo de carga',!String(t.prazo||'').trim()&&'prazo'].filter(Boolean);}
function filtrarTransportadoras(ts,q='',uf='',carga='',situacao='ativa'){
  const termo=chaveNome(q);
  return ts.filter(t=>(situacao==='todas'||(situacao==='arquivada'?t.ativo===false:t.ativo!==false))&&(!uf||(t.ufs||[]).includes(uf))&&(!carga||(t.tiposCarga||[]).includes(carga))&&chaveNome([t.nome,t.contato,t.regioes,t.rotas,t.cargas,...(t.ufs||[]),...(t.tiposCarga||[])].join(' ')).includes(termo)).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));
}
function comprasAguardandoTransporte(ocs=lista('oc'),transportadoraId=''){
  return ocs.filter(o=>SIT_ESPERANDO.includes(o.situacao)&&(!transportadoraId||o.transportadoraId===transportadoraId)).map(o=>({oc:o,itens:saldoMaterial(o).itens.filter(i=>i.falta>0)})).filter(x=>x.itens.length).sort((a,b)=>String(a.oc.entregaPrevista||'9999').localeCompare(String(b.oc.entregaPrevista||'9999')));
}
function celulaCsvTransporte(v){const s=String(v??'');return '"'+(/^[\s]*[=+@\-]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';}
function csvFretes(movs,nomeTransp=id=>(achar('transp',id)||{}).nome||'Não vinculada'){
  const linhas=[['Data da entrega','Transportadora','Compra','Origem','Destino','Conteúdo','Custeio','Valor registrado (R$)','Previsão informada','Ocorrência','Situação da ocorrência','Documento']];
  for(const r of movs)linhas.push([r.dataEntrega,nomeTransp(r.transportadoraId),r.codigo||'Avulsa',r.origem,r.destino,r.conteudo,r.custeio,custoFretePendente(r)||r.custeio!=='empresa'?'':r.valor.toFixed(2).replace('.',','),r.dataPrevista,r.ocorrencia||'nenhuma',r.ocorrencia&&r.ocorrencia!=='nenhuma'?(r.ocorrenciaStatus||'aberta'):'',r.documento]);
  return '\uFEFF'+linhas.map(l=>l.map(celulaCsvTransporte).join(';')).join('\r\n');
}
function chaveFrete(ocId,recebimentoId){return 'rec-'+encodeURIComponent(ocId)+'|'+encodeURIComponent(recebimentoId);}
function recebimentosTransporte(ocs=lista('oc')){
  return ocs.flatMap(o=>(o.recebimentos||[]).filter(r=>r.id).map(r=>({id:chaveFrete(o.id,r.id),ocId:o.id,recebimentoId:r.id,codigo:o.codigo,transportadoraId:r.transportadoraId||'',dataEntrega:dataEntregaLocal(r.em),fornecedorId:o.fornecedorId,fornecedor:(o.fornecedor||{}).nome,origem:(o.fornecedor||{}).nome||'',destino:o.obra||'',conteudo:(r.itens||[]).map(i=>fmt.numero(i.qtd)+' '+(i.unid||'')+' '+(i.descricao||(o.itens||[]).find(x=>x.id===i.itemId)?.descricao||'Material')).join('; '),valor:null,custeio:'a_definir'})));
}
function movimentosTransporte(ocs=lista('oc'),fretes=lista('frete')){
  const base=new Map(recebimentosTransporte(ocs).map(r=>[r.id,r]));
  for(const f of fretes){
    if(f.ativo===false||f.apagadoEm)continue;
    if(f.ocId&&f.recebimentoId){const k=chaveFrete(f.ocId,f.recebimentoId),r=base.get(k);if(r)base.set(k,{...r,...f,id:k,dataEntrega:r.dataEntrega,conteudo:r.conteudo,codigo:r.codigo});}
    else if(!f.ocId&&!f.recebimentoId)base.set(f.id,{...f});
  }
  return [...base.values()].sort((a,b)=>String(b.dataEntrega).localeCompare(String(a.dataEntrega)));
}
function resumoFretes(movs){return movs.reduce((s,r)=>{s.entregas++;if(r.custeio==='incluso'||r.custeio==='terceiro')s.semCobranca++;else if(r.custeio==='empresa'&&typeof r.valor==='number'&&Number.isFinite(r.valor)&&r.valor>=0)s.gasto+=r.valor;else s.pendentes++;return s;},{entregas:0,gasto:0,pendentes:0,semCobranca:0});}
let mesTransportes='';
function htmlResumoFretes(r){return '<div class="rede-indicadores"><div class="cartao"><span>Entregas no mês</span><strong>'+r.entregas+'</strong></div><div class="cartao"><span>Gasto registrado</span><strong>'+fmt.brl(r.gasto)+'</strong><small>Frete cobrado da Impresilk</small></div><div class="cartao"><span>A conferir</span><strong>'+r.pendentes+'</strong><small>Valor ou responsável não informado</small></div><div class="cartao"><span>Sem cobrança separada</span><strong>'+r.semCobranca+'</strong><small>Incluso na compra ou pago por terceiro</small></div></div>';}
function editarTransportadora(id){
  const t=achar('transp',id)||{};
  const checks=(campoNome,opcoes,marcados)=>'<div class="transp-checks">'+opcoes.map((v,i)=>'<label><input type="checkbox" data-grupo="'+campoNome+'" value="'+esc(v)+'"'+(marcados.includes(v)?' checked':'')+'>'+esc(v)+'</label>').join('')+'</div>';
  const modal=abrirModal({titulo:id?'Editar transportadora':'Nova transportadora',largo:true,corpo:'<div id="redeForm"><h3>Quem atende a Impresilk</h3><div class="linha">'+campo('Nome',entrada('nome',t.nome))+campo('CNPJ',entrada('cnpj',t.cnpj))+'</div><div class="linha">'+campo('Contato comercial',entrada('contato',t.contato))+campo('Telefone',entrada('telefone',t.telefone,{tipo:'tel'}))+'</div><div class="linha">'+campo('E-mail de atendimento',entrada('email',t.email,{tipo:'email'}))+campo('Contato de cobrança',entrada('cobranca',t.cobranca))+'</div><h3>Cobertura e operação</h3><p class="legenda">Marque somente a cobertura confirmada. Informe cidades e restrições abaixo; uma UF não significa atendimento em todas as cidades.</p>'+campo('Estados atendidos',checks('ufs',UFS_TRANSPORTE,t.ufs||[]))+campo('Cidades, regiões e restrições',areaTexto('regioes',t.regioes,'Cidades, interior/capital, áreas não atendidas…'))+campo('Rotas / origem e destino',areaTexto('rotas',t.rotas,'Ex.: São Paulo → Belo Horizonte; fornecedores onde coleta…'))+campo('Tipos de carga confirmados',checks('tiposCarga',CARGAS_TRANSPORTE,t.tiposCarga||[]))+campo('O que traz para a Impresilk',areaTexto('cargas',t.cargas,'Detalhe os materiais, fornecedores e cuidados habituais.'))+'<div class="linha">'+campo('Prazo habitual',entrada('prazo',t.prazo,{placeholder:'Ex.: 2 a 3 dias úteis após coleta'}))+campo('Frequência / dias de coleta',entrada('frequencia',t.frequencia))+'</div><div class="linha">'+campo('Comprimento máximo aceito (m)',entrada('comprimentoMax',t.comprimentoMax?paraCampo(t.comprimentoMax):'',{inputmode:'decimal',placeholder:'Em branco = não confirmado'}))+campo('Coleta / entrega agendada',seletor('agendamento',t.agendamento||'nao_informado',[{v:'nao_informado',t:'Não confirmado'},{v:'sim',t:'Disponível'},{v:'nao',t:'Não disponível'}]))+'</div>'+campo('Link de rastreamento',entrada('rastreamentoUrl',t.rastreamentoUrl,{tipo:'url',placeholder:'https://…'}))+campo('Cuidados, seguro e condições de cobrança',areaTexto('caracteristicas',t.caracteristicas,'Proteção das chapas, limites de peso, seguro a confirmar, frete mínimo, reentrega, descarga…'))+campo('Situação',seletor('situacao',t.ativo===false?'inativo':'ativo',[{v:'ativo',t:'Ativa'},{v:'inativo',t:'Arquivada — mantém entregas e gastos'}]))+'</div>',acoes:[{texto:'Cancelar',aoClicar:f=>fecharEste(f)},{texto:'Salvar transportadora',classe:'primario',aoClicar:f=>{
    const raiz=f.querySelector('#redeForm'),d=lerCampos(raiz);if(!d.nome.trim()){toast('Informe o nome da transportadora.','ruim');return;}
    const cnpj=d.cnpj.replace(/\D/g,'');if(cnpj&&lista('transp').some(x=>x.id!==id&&String(x.cnpj||'').replace(/\D/g,'')===cnpj)){toast('Este CNPJ já tem um cadastro.','ruim');return;}
    if(d.rastreamentoUrl&&!urlCatalogo(d.rastreamentoUrl)){toast('Use um link de rastreamento http ou https.','ruim');return;}
    if(d.comprimentoMax&&(!/^\d+(?:[.,]\d+)?$/.test(d.comprimentoMax)||Number(d.comprimentoMax.replace(',','.'))<=0)){toast('Informe um comprimento positivo ou deixe em branco.','ruim');return;}
    const ufs=[...raiz.querySelectorAll('[data-grupo="ufs"]:checked')].map(e=>e.value),tiposCarga=[...raiz.querySelectorAll('[data-grupo="tiposCarga"]:checked')].map(e=>e.value);
    salvar('transp',{...t,...d,nome:d.nome.trim(),ufs,tiposCarga,comprimentoMax:d.comprimentoMax?Number(d.comprimentoMax.replace(',','.')):null,rastreamentoUrl:urlCatalogo(d.rastreamentoUrl),cadastroConferidoEm:new Date().toISOString(),ativo:d.situacao==='ativo'});fecharEste(f);render();
  }}]});ligarRotulosRede(modal);
}
function editarFrete(id,transportadoraId){
  const mov=movimentosTransporte().find(x=>x.id===id)||{},ant=achar('frete',id)||{};
  const recs=recebimentosTransporte();
  const ts=opcoesRede('transp');const tid=mov.transportadoraId||transportadoraId;if(tid&&!ts.some(x=>x.v===tid)){const t=achar('transp',tid);if(t)ts.push({v:tid,t:t.nome+' (arquivada)'});}
  const fundo=abrirModal({titulo:id?'Conferir entrega e frete':'Registrar entrega / frete',largo:true,corpo:'<div id="redeForm">'+campo('Transportadora',seletor('transportadoraId',tid,ts,'Escolha a transportadora'))+campo('Vincular a um recebimento',seletor('recebimento',mov.recebimentoId?mov.id:'',recs.filter(r=>!achar('frete',r.id)||r.id===id).map(r=>({v:r.id,t:(r.codigo||'OC')+' · '+fmt.data(r.dataEntrega)+' · '+r.conteudo.slice(0,90)})),'Entrega avulsa — sem recebimento vinculado'))+ '<div class="linha">'+campo('Data da entrega',entrada('dataEntrega',mov.dataEntrega||hojeISO(),{tipo:'date'}))+campo('Fornecedor (opcional)',seletor('fornecedorId',mov.fornecedorId,opcoesRede('forn'),'Não informado'))+'</div><div class="linha">'+campo('Origem / coleta',entrada('origem',mov.origem))+campo('Destino',entrada('destino',mov.destino))+'</div>'+campo('O que trouxe',areaTexto('conteudo',mov.conteudo))+'<div class="linha">'+campo('Responsável pelo frete',seletor('custeio',mov.custeio||'a_definir',[{v:'a_definir',t:'Ainda não informado'},{v:'empresa',t:'Cobrado da Impresilk'},{v:'incluso',t:'Incluso no valor da compra'},{v:'terceiro',t:'Pago por terceiro'}]))+campo('Valor do frete (R$)',entrada('valor',mov.valor==null?'':paraCampo(mov.valor),{inputmode:'decimal',placeholder:'Em branco = não informado'}))+'</div>'+campo('Documento / CT-e (opcional)',entrada('documento',mov.documento))+'<h3>Prazo e qualidade da entrega</h3>'+campo('Data prometida para esta entrega (opcional)',entrada('dataPrevista',mov.dataPrevista,{tipo:'date'}),'Preencha a data combinada, não uma estimativa atual. Sem essa informação, a entrega não entra na pontualidade.')+'<div class="linha">'+campo('Ocorrência',seletor('ocorrencia',mov.ocorrencia||'nenhuma',[{v:'nenhuma',t:'Sem ocorrência registrada'},{v:'avaria',t:'Avaria'},{v:'falta',t:'Falta de volumes'},{v:'atraso',t:'Atraso comunicado'},{v:'outro',t:'Outra ocorrência'}]))+campo('Tratamento da ocorrência',seletor('ocorrenciaStatus',mov.ocorrenciaStatus||'aberta',[{v:'aberta',t:'A resolver'},{v:'resolvida',t:'Resolvida'}]))+'</div>'+campo('Observações / solução adotada',areaTexto('obs',mov.obs))+'</div><p class="legenda">A entrega vinculada usa a data e os itens do recebimento. Este controle não altera o total da ordem de compra nem confirma pagamento.</p>',acoes:[{texto:'Cancelar',aoClicar:f=>fecharEste(f)},{texto:'Salvar registro',classe:'primario',aoClicar:f=>{
    const d=lerCampos(f.querySelector('#redeForm')),rec=recs.find(r=>r.id===d.recebimento);
    if(!d.transportadoraId||(!rec&&(!dataFreteValida(d.dataEntrega)||!d.conteudo.trim()))){toast('Informe transportadora, data válida e o que foi entregue.','ruim');return;}
    if(d.dataPrevista&&!dataFreteValida(d.dataPrevista)){toast('Informe uma previsão válida ou deixe em branco.','ruim');return;}
    if(mov.recebimentoId&&d.recebimento!==mov.id){toast('Este registro já está vinculado. Edite os dados sem trocar o recebimento.','ruim');return;}
    if(id&&!mov.recebimentoId&&rec){toast('Um registro avulso deve continuar avulso. Edite o recebimento separadamente.','ruim');return;}
    const texto=String(d.valor).trim(),valor=texto?numeroBR(texto):null;
    if(texto&&(!/^-?\d[\d.,\s]*$/.test(texto)||!Number.isFinite(valor)||valor<0)){toast('Informe um valor válido, sem sinal negativo.','ruim');return;}
    if(rec&&achar('frete',rec.id)&&rec.id!==id){toast('Este recebimento já tem um frete. Abra o registro existente.','ruim');return;}
    salvar('frete',{...ant,...d,id:rec?rec.id:(id||undefined),ocId:rec?rec.ocId:'',recebimentoId:rec?rec.recebimentoId:'',dataEntrega:rec?rec.dataEntrega:d.dataEntrega,conteudo:rec?rec.conteudo:d.conteudo,valor:d.custeio==='empresa'?valor:null,ativo:true});fecharEste(f);render();
  }}]});
  ligarRotulosRede(fundo);
  const raiz=fundo.querySelector('#redeForm'),sel=raiz.querySelector('[data-campo="recebimento"]');
  if(id)sel.disabled=true;
  function aplicarRec(preencher=false){const r=recs.find(x=>x.id===sel.value);for(const k of ['dataEntrega','conteudo']){const i=raiz.querySelector('[data-campo="'+k+'"]');i.readOnly=!!r;if(r)i.value=r[k];}if(r&&preencher)for(const k of ['origem','destino','fornecedorId'])raiz.querySelector('[data-campo="'+k+'"]').value=r[k]||'';}
  sel.onchange=()=>aplicarRec(true);aplicarRec();
  const ocorrencia=raiz.querySelector('[data-campo="ocorrencia"]'),tratamento=raiz.querySelector('[data-campo="ocorrenciaStatus"]');function atualizarOcorrencia(){tratamento.disabled=ocorrencia.value==='nenhuma';}ocorrencia.onchange=atualizarOcorrencia;atualizarOcorrencia();
  const pag=raiz.querySelector('[data-campo="custeio"]'),val=raiz.querySelector('[data-campo="valor"]');function atualizarValor(){val.disabled=pag.value!=='empresa';}pag.onchange=atualizarValor;atualizarValor();
}
function htmlInteligenciaTransportes(movs){
  const i=inteligenciaFretes(movs);
  return '<div class="transp-leitura"><div><span>⏱ Pontualidade</span><strong>'+(i.mensurados?Math.round(i.noPrazo/i.mensurados*100)+'%':'Sem base')+'</strong><small>'+(i.mensurados?i.noPrazo+' de '+i.mensurados+' entregas com data prometida':'Informe a data prometida ao conferir a entrega')+'</small></div><div><span>R$ Médio por frete</span><strong>'+(i.media==null?'Sem valores':fmt.brl(i.media))+'</strong><small>'+i.custos+' fretes cobrados com valor informado</small></div><div><span>⚑ Ocorrências abertas</span><strong>'+i.ocorrencias+'</strong><small>Avarias, faltas e outros casos a resolver</small></div></div>';
}
function htmlCoberturaTransportadora(t){
  const pend=pendenciasCadastroTransporte(t);
  const contato=[t.contato,t.telefone,t.email].filter(Boolean).join(' · '),url=urlCatalogo(t.rastreamentoUrl);
  return '<section class="cartao"><div class="rede-titulo"><div><span class="rede-kicker">🚚 Cobertura e operação</span><h2>'+esc(t.nome)+'</h2></div><span class="etiqueta">'+(t.ativo===false?'Arquivada':'Ativa')+'</span></div><div class="transp-ufs">'+(t.ufs||[]).map(u=>'<span>'+esc(u)+'</span>').join('')+'</div><div class="rede-cobertura">'+[['📍 Regiões e restrições',t.regioes],['↔ Rotas',t.rotas],['📦 Cargas',[...(t.tiposCarga||[]),t.cargas].filter(Boolean).join(' · ')],['⏱ Prazo e frequência',[t.prazo,t.frequencia].filter(Boolean).join(' · ')],['☎ Atendimento',contato],['R$ Cobrança',t.cobranca],['↔ Comprimento máximo',t.comprimentoMax?t.comprimentoMax+' m':''],['▣ Agendamento',t.agendamento==='sim'?'Disponível':t.agendamento==='nao'?'Não disponível':''],['ℹ Cuidados e condições',t.caracteristicas]].map(([a,b])=>'<div><h3>'+a+'</h3><p>'+esc(b||'Ainda não informado')+'</p></div>').join('')+'</div><div class="rede-titulo">'+(url?'<a class="btn" href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">Abrir rastreamento ↗</a>':'')+'<span class="legenda">'+(t.cadastroConferidoEm?'Cadastro revisado em '+fmt.data(dataEntregaLocal(t.cadastroConferidoEm)):'Cadastro ainda sem data de revisão')+'</span></div>'+(pend.length?'<p class="aviso atencao">Complete: '+esc(pend.join(', '))+'.</p>':'')+'</section>';
}
function htmlAguardandoTransporte(t){
  const ps=comprasAguardandoTransporte(lista('oc'),t?.id||'');
  return '<details class="cartao transp-aguardando"'+(ps.length?' open':'')+'><summary>🚚 Compras aguardando entrega · '+ps.length+'</summary><p class="legenda">Todos os períodos. Calculado pelo saldo dos itens; estes pedidos não entram nos gastos das entregas concluídas.</p>'+ps.map(({oc:o,itens})=>{const atraso=dataFreteValida(o.entregaPrevista)&&o.entregaPrevista<hojeISO();return '<a class="transp-pedido" href="#/compras/'+esc(o.id)+'"><div><b>'+esc(o.codigo||'Ordem de compra')+'</b><small>'+esc((achar('transp',o.transportadoraId)||{}).nome||'Transportadora ainda não definida')+' · '+esc(o.fornecedor?.nome||'Fornecedor não informado')+'</small><p>'+esc(itens.map(i=>fmt.numero(i.falta)+' '+(i.unid||'')+' '+i.descricao).join('; '))+'</p></div><span class="'+(atraso?'transp-atraso':'legenda')+'">'+(dataFreteValida(o.entregaPrevista)?(atraso?'Previsão vencida · ':'Previsto · ')+fmt.data(o.entregaPrevista):'Previsão não informada')+'</span></a>';}).join('')+(!ps.length?'<p class="legenda">Sem compras com saldo pendente neste recorte.</p>':'')+'</details>';
}
function htmlMovimentoTransporte(r){
  const ocorrencia=r.ocorrencia&&r.ocorrencia!=='nenhuma',atraso=dataFreteValida(r.dataPrevista)&&dataFreteValida(r.dataEntrega)&&r.dataEntrega>r.dataPrevista;
  return '<article class="transp-entrega"><div class="transp-entrega-data"><b>'+fmt.data(r.dataEntrega)+'</b>'+(r.ocId?'<a href="#/compras/'+esc(r.ocId)+'">'+esc(r.codigo||'Ver compra')+'</a>':'<small>Entrega avulsa</small>')+'</div><div class="transp-entrega-corpo"><b>'+esc((achar('transp',r.transportadoraId)||{}).nome||'Transportadora não vinculada')+'</b><small>'+esc(r.origem||'Origem não informada')+' → '+esc(r.destino||'Destino não informado')+'</small><p>'+esc(r.conteudo)+'</p><div class="transp-sinais">'+(dataFreteValida(r.dataPrevista)?'<span class="'+(atraso?'transp-atraso':'')+'">'+(atraso?'Após o prazo':'Dentro do prazo')+' · prometido '+fmt.data(r.dataPrevista)+'</span>':'<span>Sem data prometida</span>')+(ocorrencia?'<span class="'+(r.ocorrenciaStatus==='resolvida'?'':'transp-atraso')+'">'+esc(r.ocorrencia)+' · '+(r.ocorrenciaStatus==='resolvida'?'resolvida':'a resolver')+'</span>':'')+'</div></div><div class="transp-entrega-valor"><strong>'+(custoFretePendente(r)?'A conferir':r.custeio==='empresa'?fmt.brl(r.valor):r.custeio==='incluso'?'Incluso na compra':'Pago por terceiro')+'</strong><small>'+esc(r.documento||'Documento não informado')+'</small><button class="btn pequeno" data-frete="'+esc(r.id)+'">Conferir entrega</button></div></article>';
}
TELAS.transportadoras=function(el,args){
  const t=args[0]?achar('transp',args[0]):null,mes=/^\d{4}-(0[1-9]|1[0-2])$/.test(args[1]||'')?args[1]:(mesTransportes||hojeISO().slice(0,7)),todos=movimentosTransporte(),movs=todos.filter(r=>String(r.dataEntrega||'').slice(0,7)===mes&&(!t||r.transportadoraId===t.id));
  cabecalho(t?t.nome:'Transportadoras',t?'Cobertura confirmada, compras a caminho e histórico de entregas.':'Encontre quem transporta seu material e acompanhe prazos e fretes.',t?'<a class="btn" href="#/transportadoras">← Transportadoras</a><button class="btn" id="editarTransp">Editar cadastro</button><button class="btn primario" id="novoFrete">+ Registrar entrega</button>':'<button class="btn" id="novoFrete">+ Registrar entrega</button><button class="btn primario" id="novaTransp">+ Nova transportadora</button>');
  el.innerHTML=navRede('transportadoras')+(t?htmlCoberturaTransportadora(t):'<section class="cartao transp-diretorio"><div class="rede-titulo"><div><span class="rede-kicker">Escolher transportadora</span><h2>Quem atende sua carga?</h2></div><span class="legenda">Ordem A–Z</span></div><div class="transp-filtros">'+campo('Nome, cidade ou rota','<input id="buscaTransp" type="search" placeholder="Ex.: São Paulo, chapas…">')+campo('Estado confirmado',seletor('ufFiltro','',UFS_TRANSPORTE,'Todos os estados'))+campo('Carga confirmada',seletor('cargaFiltro','',CARGAS_TRANSPORTE,'Todos os tipos'))+campo('Cadastro',seletor('situacaoFiltro','ativa',[{v:'ativa',t:'Ativas'},{v:'todas',t:'Todas'},{v:'arquivada',t:'Arquivadas'}]))+'</div><p class="legenda" id="transpResultado" role="status"></p><div id="transpDiretorio"></div><p class="legenda">Os filtros de estado e carga usam apenas os campos marcados no cadastro. Confira a cidade, a rota e os limites antes de contratar.</p></section>')+htmlAguardandoTransporte(t)+'<div class="rede-titulo"><div><span class="rede-kicker">Histórico mensal</span><h2>O que chegou e quanto custou</h2></div><div class="acoes">'+campo('Mês de entrega','<input id="mesTransportes" type="month" value="'+esc(mes)+'">')+'<button class="btn" id="exportarFretes">Exportar mês</button></div></div>'+htmlResumoFretes(resumoFretes(movs))+htmlInteligenciaTransportes(movs)+'<p class="legenda">Gastos registrados, sem confirmar pagamento. Valores ausentes ficam a conferir. Pontualidade considera somente entregas com data prometida informada.</p>';
  const sem=movs.filter(r=>!r.transportadoraId);if(sem.length)el.innerHTML+='<div class="aviso atencao">'+sem.length+' recebimento(s) sem transportadora neste mês. Use “Conferir entrega” para vincular.</div>';
  el.innerHTML+='<section class="cartao"><div class="rede-titulo"><h3>📦 Entregas do mês</h3>'+campo('Exibir entregas',seletor('filtroFretes','todas',[{v:'todas',t:'Todas'},{v:'pendentes',t:'Frete a conferir'},{v:'ocorrencias',t:'Ocorrências abertas'},{v:'atrasadas',t:'Após a data prometida'},{v:'semTransp',t:'Sem transportadora'}]))+'</div><div id="listaFretes"></div></section>';
  ligarRotulosRede(el);
  const filtro=el.querySelector('[data-campo="filtroFretes"]');
  function mostrarFretes(){const filtrados=movs.filter(r=>filtro.value==='todas'||filtro.value==='pendentes'&&custoFretePendente(r)||filtro.value==='ocorrencias'&&r.ocorrencia&&r.ocorrencia!=='nenhuma'&&r.ocorrenciaStatus!=='resolvida'||filtro.value==='atrasadas'&&dataFreteValida(r.dataPrevista)&&r.dataEntrega>r.dataPrevista||filtro.value==='semTransp'&&!r.transportadoraId);el.querySelector('#listaFretes').innerHTML=filtrados.map(htmlMovimentoTransporte).join('')||'<p class="legenda">Nenhuma entrega neste filtro.</p>';el.querySelectorAll('[data-frete]').forEach(b=>b.onclick=()=>editarFrete(b.dataset.frete,t?.id));}
  filtro.onchange=mostrarFretes;mostrarFretes();
  if(!t){
    const busca=el.querySelector('#buscaTransp'),uf=el.querySelector('[data-campo="ufFiltro"]'),carga=el.querySelector('[data-campo="cargaFiltro"]'),situacao=el.querySelector('[data-campo="situacaoFiltro"]');
    function mostrarDiretorio(){const ts=filtrarTransportadoras(lista('transp'),busca.value,uf.value,carga.value,situacao.value);el.querySelector('#transpResultado').textContent=ts.length+' transportadora(s) encontrada(s)';el.querySelector('#transpDiretorio').innerHTML=ts.map(x=>{const p=pendenciasCadastroTransporte(x);return '<a class="transp-card" href="#/transportadoras/'+esc(x.id)+'"><span class="produto-simbolo" aria-hidden="true">🚚</span><div><h3>'+esc(x.nome)+'</h3><p>'+esc([...(x.ufs||[]),x.regioes].filter(Boolean).join(' · ')||'Cobertura ainda não informada')+'</p><small>'+esc([...(x.tiposCarga||[]),x.cargas].filter(Boolean).join(' · ')||'Cargas ainda não informadas')+'</small></div><div class="transp-card-apoio"><b>'+esc(x.prazo||'Prazo a confirmar')+'</b><small>'+esc(p.length?'Completar '+p.join(', '):x.frequencia||'Cadastro operacional preenchido')+'</small><span>Ver ficha e gastos →</span></div></a>';}).join('')||'<div class="rede-vazio">Nenhuma transportadora com esses filtros. Ajuste a busca ou cadastre a cobertura confirmada.</div>';}
    busca.oninput=mostrarDiretorio;for(const e of [uf,carga,situacao])e.onchange=mostrarDiretorio;mostrarDiretorio();
  }
  document.getElementById('mesTransportes').onchange=e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)){mesTransportes=e.target.value;if(args[1])location.hash='#/transportadoras/'+(t?.id||'todas')+'/'+mesTransportes;else render();}};
  document.getElementById('exportarFretes').onclick=()=>{if(!movs.length){toast('Não há entregas neste mês.');return;}salvarNoAparelho(new Blob([csvFretes(movs)],{type:'text/csv;charset=utf-8'}),'fretes-'+mes+(t?'-'+String(t.nome).replace(/[^a-zA-Z0-9-]/g,'_'):'')+'.csv');};
  document.getElementById('novoFrete').onclick=()=>editarFrete(null,t?.id);const n=document.getElementById('novaTransp');if(n)n.onclick=()=>editarTransportadora(null);const ed=document.getElementById('editarTransp');if(ed)ed.onclick=()=>editarTransportadora(t.id);
};
