import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
const {JSDOM}=createRequire(import.meta.url)('jsdom');
const clone=x=>JSON.parse(JSON.stringify(x));
function cliente(seed={}){
 const dom=new JSDOM('<body><main id="pagina"></main></body>',{runScripts:'outside-only',url:'https://test.invalid/'}),w=dom.window;
 w.S={cfg:{empresa:{nomeCurto:'Teste'},obras:[],unidades:['un','kg','m²']},reg:clone(seed),quem:'Teste',_catalogo:{produtos:[]}};
 w.eval(['ui.js','qualificacao.js','compras.js','rede.js','cotacao.js'].map(f=>readFileSync((process.argv[2] && ['compras.js','cotacao.js'].includes(f) ? process.argv[2]+'/' : '')+f,'utf8')).join('\n'));
 w.lista=c=>w.S.reg[c]||[];w.achar=(c,id)=>w.lista(c).find(x=>x.id===id);w.podeVer=()=>true;w.ehDirecao=()=>true;
 w.historiar=(r,t)=>[...(r.historico||[]),{o_que:t}];w.irPara=()=>{};w.render=()=>{};w.cabecalho=(t,s,acoes='')=>{let h=w.document.querySelector('header');if(!h){h=w.document.createElement('header');w.document.body.prepend(h);}h.innerHTML=acoes;};
 w.toasts=[];w.toast=t=>w.toasts.push(t);w.confirmar=async()=>true;w.perguntar=async()=> 'Sem restante';w.hojeISO=()=> '2026-10-05';
 w.gravacoes=[];w.salvar=(c,r)=>{r=clone(r);r.id||='novo-'+w.gravacoes.length;w.gravacoes.push({c,r});const arr=w.S.reg[c]||=[];const i=arr.findIndex(x=>x.id===r.id);if(i<0)arr.push(r);else arr[i]=r;return r;};
 w.abrirModal=opcoes=>{const fundo=w.document.createElement('div');fundo.innerHTML=opcoes.corpo;w.document.body.appendChild(fundo);w.modal={opcoes,fundo};return fundo;};
 w.fecharEste=f=>f.remove();w.fecharModal=()=>w.modal?.fundo.remove();
 return w;
}
const sc={id:'s1',situacao:'aprovada',itens:[{id:'i1',descricao:'Material A',qtd:10,unid:'un'}]};
const cot={id:'c1',situacao:'aberta',scIds:['s1'],itens:[{...sc.itens[0],origemScId:'s1',origemScItemId:'i1'}],fornecedores:[{id:'f1',fornecedorId:'forn1',nome:'Fornecedor A',respondidoEm:'2026-10-05',precos:{i1:10}}]};
const oc={id:'o1',situacao:'confirmada',scIds:['s1'],fornecedorId:'forn1',fornecedor:{nome:'Fornecedor A'},itens:[{...cot.itens[0],preco:10}],recebimentos:[]};
let checks=0,failures=0;
async function test(n,fn){try{await fn();checks++;console.log('✓ '+n);}catch(e){failures++;console.error('✗ '+n+' — '+e.message);}}
await test('Escolher cotação bloqueia saldo já comprado por OC direta',async()=>{const w=cliente({sc:[sc],cot:[cot],oc:[oc]});await w.escolherFornecedor(w.S.reg.cot[0],'f1');assert.equal(w.gravacoes.length,0);assert(w.toasts.some(t=>/saldo|comprad/i.test(t)));});
await test('Escolher proposta reconfere o saldo após o diálogo',async()=>{const w=cliente({sc:[sc],cot:[cot],oc:[]});w.perguntar=async()=>{w.S.reg.oc.push(clone(oc));return 'Melhor preço';};await w.escolherFornecedor(w.S.reg.cot[0],'f1');assert.equal(w.gravacoes.length,0);});
await test('Cotação reduzida na SC não compra a quantidade antiga',async()=>{const s=clone(sc);s.itens[0].qtd=3;const w=cliente({sc:[s],cot:[cot],oc:[]});await w.escolherFornecedor(w.S.reg.cot[0],'f1');assert.equal(w.gravacoes.length,0);});
await test('Nova tentativa da mesma cotação abre OC existente sem reescrever itens',async()=>{const o={...clone(oc),id:'cot-c1',cotacaoId:'c1',itens:[{...oc.itens[0],qtd:3,preco:9}]};const w=cliente({cot:[cot],sc:[sc],oc:[o]});await w.escolherFornecedor(w.S.reg.cot[0],'f1');assert.equal(w.gravacoes.length,0);assert.equal(w.S.reg.oc[0].itens[0].qtd,3);});
await test('Compra por cotação irmã consome o teto da família sem SC',()=>{const root={...clone(cot),scIds:[],situacao:'aprovada'},a={...clone(cot),id:'c2',scIds:[],cotacaoOrigemId:'c1',itens:[{...cot.itens[0],qtd:6}]},b={...clone(a),id:'c3'};const w=cliente({cot:[root,a,b],oc:[{...clone(oc),cotacaoId:'c1',scIds:[],itens:[{...oc.itens[0],qtd:4}]},{...clone(oc),id:'o2',cotacaoId:'c3',scIds:[],itens:[{...oc.itens[0],qtd:6}]}]});assert.equal(w.itensPendentesCotacao(w.S.reg.cot[1]).length,0);});
await test('Recebimento excedente atende SC apenas até o limite da OC',()=>{const o={...clone(oc),situacao:'entregue',itens:[{...oc.itens[0],qtd:5}],recebimentos:[{id:'r1',itens:[{itemId:'i1',qtd:10}]}]};const w=cliente({sc:[sc],oc:[o]});const s=w.saldoScPorItem(w.S.reg.sc[0])[0];assert.equal(s.recebido,5);assert.equal(s.faltaComprar,5);w.recalcularSC('s1');assert.equal(w.S.reg.sc[0].situacao,'em_compra');});
await test('Saldo de cotação também limita excedente à quantidade comprada',()=>{const o={...clone(oc),cotacaoId:'c1',situacao:'entregue',itens:[{...oc.itens[0],qtd:5}],recebimentos:[{id:'r1',itens:[{itemId:'i1',qtd:10}]}]};const w=cliente({cot:[{...cot,scIds:[]}],oc:[o]});assert.equal(w.itensPendentesCotacao(w.S.reg.cot[0])[0]?.qtd,5);});
await test('Cancelar depois de receber encerra apenas saldo e conserva o recebido',async()=>{const o={...clone(oc),situacao:'parcial',recebimentos:[{id:'r1',itens:[{itemId:'i1',qtd:4,unid:'un'}]}]};const w=cliente({sc:[sc],oc:[o]});await w.avancarOC(w.S.reg.oc[0],'cancelada');assert.equal(w.S.reg.oc[0].situacao,'entregue');assert(w.S.reg.oc[0].encerradaComFalta);assert.equal(w.saldoScPorItem(w.S.reg.sc[0])[0].faltaComprar,6);});
await test('Botão de cancelar não permanece genérico quando houve recebimento',()=>{const w=cliente();const html=w.botoesFluxoOC({...oc,situacao:'parcial',recebimentos:[{id:'r1',itens:[{itemId:'i1',qtd:4}]}]});assert(!html.includes('data-fluxo="cancelada"'));assert.match(html,/Encerrar.*falta|saldo restante/i);});
await test('Item recebido bloqueia troca de unidade e material no editor',()=>{const w=cliente({oc:[{...clone(oc),recebimentos:[{id:'r1',itens:[{itemId:'i1',qtd:4}]}]}]});w.S.ocEditando=w.S.reg.oc[0];const root=w.document.createElement('div');root.id='itensOC';root.innerHTML=w.linhaItem(w.S.reg.oc[0].itens[0],true);w.document.body.appendChild(root);w.ligarItens(root,true);assert.equal(root.querySelector('[data-i="unid"]').disabled,true);assert.equal(root.querySelector('[data-i="materialId"]').disabled,true);});
await test('Cartão de compras geradas não expõe preço nem atalho ao solicitante',()=>{const s={...clone(sc),ocIds:['o1']};const w=cliente({sc:[s],oc:[{...oc,codigo:'OC-TESTE',totalLiquido:100}]});w.podeVer=()=>false;const root=w.document.querySelector('main');w.telaSolicitacao(root,'s1');const card=[...root.querySelectorAll('.cartao')].find(c=>c.querySelector('h3')?.textContent==='Compras geradas');assert(card);assert(!/R\$|100,00/.test(card.textContent));assert.equal(card.querySelector('[data-veroc]'),null);});
await test('Compra parcial válida preserva preço, unidade e origem',async()=>{const c=clone(cot);c.itens.push({id:'i2',descricao:'Tinta',unid:'L',qtd:2});const w=cliente({sc:[sc],cot:[c],oc:[]});await w.escolherFornecedor(w.S.reg.cot[0],'f1');assert.equal(w.S.reg.oc.length,1);const i=w.S.reg.oc[0].itens[0];assert.equal(i.qtd,10);assert.equal(i.preco,10);assert.equal(i.unid,'un');assert.equal(i.origemScId,'s1');});

await test('Recebimento envia operação específica sem se apresentar como edição da OC',async()=>{const w=cliente({oc:[oc]});w.telaReceberOC(w.S.reg.oc[0]);w.modal.fundo.querySelector('[data-rec]').value='4';await w.modal.opcoes.acoes[1].aoClicar(w.modal.fundo);const r=w.gravacoes.find(g=>g.c==='oc')?.r;assert(r);assert.equal(r._operacao,'recebimento');assert.equal(r.recebimentos[0].itens[0].qtd,4);});
await test('Encerrar saldo depois de recebimento pendente não herda operação limitada',async()=>{const o={...clone(oc),_operacao:'recebimento',situacao:'parcial',recebimentos:[{id:'r1',itens:[{itemId:'i1',qtd:4}]}]};const w=cliente({oc:[o],sc:[sc]});await w.avancarOC(w.S.reg.oc[0],'encerrar');assert.notEqual(w.gravacoes.find(g=>g.c==='oc').r._operacao,'recebimento');});
await test('Editor envia versão aberta e não herda operação de recebimento',async()=>{const o={...clone(oc),versao:7,_operacao:'recebimento'},w=cliente({oc:[o],forn:[{id:'forn1',nome:'Fornecedor A',origemMubi:'101',ativo:true}],sc:[sc]});w.editorOC(w.document.querySelector('main'),'o1');w.document.querySelector('[data-i=preco]').value='11';w.S.reg.oc[0]={...w.S.reg.oc[0],versao:8};w.document.getElementById('salvarOC').click();await new Promise(r=>setTimeout(r,0));const saved=w.gravacoes.find(g=>g.c==='oc')?.r;assert(saved, w.document.getElementById('ocErro')?.textContent);assert.equal(saved._versaoBase,7);assert.equal(saved._operacao,undefined);assert.equal(saved.itens[0].preco,11);});

await test('Anexar foto usa operação de recebimento e preserva a identidade existente',async()=>{const o={...clone(oc),recebimentos:[{id:'r1',itens:[{itemId:'i1',qtd:4}],fotos:[],fotosPendentes:1}]};const w=cliente({oc:[o]});w.URL.createObjectURL=()=> 'blob:teste';w.encolherFoto=async f=>f;w.enviarArquivo=async()=>({id:'foto1'});w.anexarFotoRecebimento('o1','r1');const input=w.document.getElementById('anexFoto');Object.defineProperty(input,'files',{value:[new w.File(['imagem'],'foto.jpg',{type:'image/jpeg'})]});input.dispatchEvent(new w.Event('change'));await new Promise(r=>setTimeout(r,0));w.modal.opcoes.acoes[1].aoClicar(w.modal.fundo);const saved=w.gravacoes.find(g=>g.c==='oc')?.r;assert(saved);assert.equal(saved._operacao,'recebimento');assert.equal(saved.recebimentos[0].itens[0].qtd,4);assert.deepEqual(saved.recebimentos[0].fotos,['foto1']);});
await test('Dados da empresa incompletos aparecem apenas para quem pode configurar',()=>{const w=cliente({oc:[{...clone(oc),situacao:'rascunho'}]});w.htmlApoioOC=()=>'';w.htmlReferenciasERP=()=>'';w.ligarReferenciasERP=()=>{};w.telaOC(w.document.querySelector('main'),'o1');assert.match(w.document.querySelector('main').textContent,/Cadastro da empresa incompleto/);w.podeVer=()=>false;w.telaOC(w.document.querySelector('main'),'o1');assert(!w.document.querySelector('main').textContent.includes('Cadastro da empresa incompleto'));});
console.log(`${checks} verificações passaram; ${failures} falharam`);if(failures)process.exitCode=1;
