import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {parametrosConferencia,consultarMubi,normalizarConferencia} from '../supabase/functions/_shared/mubisys.ts';
let checks=0; const test=(name,fn)=>{fn();checks++;};
const env=k=>({MUBI_PUBLIC_KEY:'key-test',MUBI_TOKEN:'token-test'}[k]);
const valid={tipo:'contas',inicio:'2026-09-01',fim:'2026-09-07'};
test('Filtros oficiais contas',()=>assert.equal(parametrosConferencia(valid).params.filtrodata,'VENCIMENTO'));
test('Filtros oficiais notas',()=>assert.equal(parametrosConferencia({...valid,tipo:'notas'}).params.filtrodata,'ENTRADA'));
for(const body of [{...valid,tipo:'other'},{...valid,fim:'2026-09-08'},{...valid,inicio:'2026-02-30'},{...valid,pagina:1.1},{...valid,pagina:0},{...valid,inicio:'2026-09-10'}]) test('Recusa parâmetros inválidos',()=>assert.throws(()=>parametrosConferencia(body)));
let calls=0;
const r=await consultarMubi('contas-pagar',{page:'1',per_page:'100'},{env,fetch:async(url,opts)=>{calls++;assert.equal(opts.method,'GET');assert.equal(opts.redirect,'error');assert(!url.includes('token-test'));return new Response(JSON.stringify({data:[{id:1}],pagination:{current_page:1,last_page:2,total:101}}),{status:201});}});
test('Página incompleta não aparece concluída',()=>assert.equal(r.temMais,true));
await assert.rejects(()=>consultarMubi('contas-pagar',{}, {env,fetch:async()=>new Response('{}',{status:401})}),/401/);checks++;
await assert.rejects(()=>consultarMubi('contas-pagar',{}, {env,fetch:async()=>new Response('{}',{status:404})}),/404/);checks++;
await assert.rejects(()=>consultarMubi('contas-pagar',{}, {env,fetch:async()=>new Response('{}',{status:200})}),/Formato/);checks++;
await assert.rejects(()=>consultarMubi('evil',{}, {env}),/permitida/);checks++;
await assert.rejects(()=>consultarMubi('produto',{}, {env:k=>k==='MUBI_BASE_URL'?'https://example.com/api':env(k)}),/Base/);checks++;
let retries=0;
await consultarMubi('produto',{page:'1'}, {env,fetch:async()=>{retries++;return new Response(retries===1?'':JSON.stringify([]),{status:retries===1?503:200});}});
test('Retentativa limitada',()=>assert.equal(retries,2));
await assert.rejects(()=>consultarMubi('produto',{}, {env,timeoutMs:5,fetch:async(_u,o)=>new Promise((_r,reject)=>o.signal.addEventListener('abort',()=>reject(new Error('abort'))))}),/tempo/);checks++;
const doc=normalizarConferencia({id:1,valor:0,token:'oculto',outro_campo:'origem'},'notas');
test('Zero preservado',()=>assert.equal(doc.valor,0));
test('Campo ausente não vira zero',()=>assert.equal(normalizarConferencia({id:2},'contas').valor,null));
test('Campos de autenticação excluídos',()=>assert(!doc.campos.some(c=>c.campo==='token')));

const ctx=vm.createContext({console,document:{addEventListener(){}},S:{reg:{}},localStorage:{getItem(){return null}},crypto});
for(const f of ['ui.js','qualificacao.js','compras.js','inteligencia.js','rede.js','transporte.js'])vm.runInContext(readFileSync(f,'utf8'),ctx);
vm.runInContext("function lista(c){return S.reg[c]||[];} function achar(c,id){return lista(c).find(r=>r.id===id)||null;}",ctx);
const run=s=>vm.runInContext(s,ctx);
test('Entrega não medida pela edição',()=>assert.equal(run("atrasoEntregaReal({atualizadoEm:'2026-09-09',entregaPrevista:'2026-09-01'})"),null));
test('Prazo real',()=>assert.equal(run("atrasoEntregaReal({recebidoEm:'2026-09-03',entregaPrevista:'2026-09-01'})"),2));
test('Quantidade parcial',()=>assert.equal(run("saldoMaterial({itens:[{id:'a',qtd:10,preco:5}],recebimentos:[{itens:[{itemId:'a',qtd:4}]}]}).valorItens"),30));
test('Excesso não vira saldo negativo',()=>assert.equal(run("saldoMaterial({itens:[{id:'a',qtd:2,preco:5}],recebimentos:[{itens:[{itemId:'a',qtd:4}]}]}).valorItens"),0));
test('Saldo desconhecido preservado',()=>assert.equal(run("saldoMaterial({itens:[{id:'a',qtd:2}]}).valorItens"),null));
test('Duplicidade pelo ID sem CNPJ',()=>assert(run("duplicidadeFornecedor({idMubi:'1'},[{origemMubi:'1'}])")));
test('Duplicidade por CNPJ normalizado',()=>assert(run("duplicidadeFornecedor({idMubi:'2',cnpj:'12.345'},[{cnpj:'12345'}])")));
test('Nome parecido não casa sozinho',()=>assert(!run("duplicidadeFornecedor({nome:'ABC'},[{nome:'ABC'}])")));
test('Valor zero comparável',()=>assert.equal(run("compararDocumentoOC({valor:0},{totalLiquido:10}).diferenca"),-10));
test('Valor não identifica fornecedor',()=>assert.equal(run("compararDocumentoOC({valor:100},{totalLiquido:100}).identidade"),false));
run("S.reg.cot=[{fornecedores:[{fornecedorId:'f',nome:'Novo',respondidoEm:'2026-09-01'}]}]");
test('Nota provisória não vira fornecedor preferencial',()=>assert(run("htmlFornecedores([{id:'f',nome:'Novo'}])").includes('0 preferencial')));

for (const v of [' ',true,false,Infinity])test('Valor inválido não vira zero',()=>assert.equal(normalizarConferencia({valor:v},'notas').valor,null));
// Real access policy functions, with only network dependency removed.
let access=readFileSync('supabase/functions/_shared/acesso.ts','utf8').replace(/^import .*?;$/gm,'').replace(/const sb = createClient\([\s\S]*?\n\);/,'const sb = {};').replaceAll('export ','');
const ac=vm.createContext({Deno:{env:{get(){return ''}}},TextEncoder});
vm.runInContext(stripTypeScriptTypes(access),ac);
for(const perfil of ['obra','escritorio'])test('Conferência negada a '+perfil,()=>assert.equal(vm.runInContext(`podeFazer({perfil:'${perfil}'},'conferenciaMubi')`,ac),false));
test('Conferência liberada à direção',()=>assert.equal(vm.runInContext("podeFazer({perfil:'direcao'},'conferenciaMubi')",ac),true));
test('Comprador não altera referência ERP',()=>assert(vm.runInContext("motivoRecusa({perfil:'escritorio'},'oc',{referenciasErp:[{id:'x'}]}, {})",ac).includes('direção')));
console.log(`${checks} verificações de integração e inteligência passaram`);
