import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {stripTypeScriptTypes} from 'node:module';
import {validarRede,chaveRecebimento} from '../supabase/functions/_shared/rede.ts';
import {COLECOES} from '../supabase/functions/_shared/colecoes.ts';
let n=0;const test=(nome,fn)=>{fn();n++;};
const ctx=vm.createContext({console,Intl,URL,document:{addEventListener(){}},S:{reg:{}},localStorage:{getItem(){return null}},crypto});
for(const f of ['ui.js','rede.js','transporte.js'])vm.runInContext(readFileSync(f,'utf8'),ctx);
vm.runInContext(`function lista(c){return (S.reg[c]||[]).filter(r=>!r.apagadoEm)};function achar(c,id){return lista(c).find(r=>r.id===id)||null};`,ctx);
const run=s=>vm.runInContext(s,ctx);
run(`S.reg={mat:[{id:'m1',nome:'ACM branco 3 mm',unidade:'un'}],oferta:[{id:'a1',fornecedorId:'f1',materialId:'m1',unidade:'un',nomeFornecedor:'Alupainel Branco',codigo:'A-3'}],forn:[{id:'f1',nome:'Exemplo'}],transp:[],proj:[]};`);
test('Alias só por identidade explícita',()=>assert.equal(run(`ofertaMaterial('f1',{descricao:'ACM branco 3 mm',unid:'un'})`),null));
test('Unidade diferente não é equivalência',()=>assert.equal(run(`ofertaMaterial('f1',{materialId:'m1',unid:'m'})`),null));
test('Nome comercial vinculado',()=>assert.equal(run(`ofertaMaterial('f1',{materialId:'m1',unid:'un'}).nomeFornecedor`),'Alupainel Branco'));
run(`var snapshot=nomesParaFornecedor('f1',[{id:'i1',materialId:'m1',unid:'un'}]); S.reg.oferta[0].nomeFornecedor='Nome atualizado';`);
test('Alteração de catálogo não muda convite anterior',()=>assert.equal(run(`snapshot.i1.nome`),'Alupainel Branco'));
test('Outro fornecedor não recebe alias alheio',()=>assert.equal(run(`Object.keys(nomesParaFornecedor('f2',[{id:'i1',materialId:'m1',unid:'un'}])).length`),0));
for(const u of ['javascript:alert(1)','data:text/html,abc','https://user:pass@example.com',''])test('Link inseguro recusado',()=>assert.equal(run(`urlCatalogo(${JSON.stringify(u)})`),''));
test('Link https válido',()=>assert.equal(run(`urlCatalogo('https://example.com/catalogo.pdf')`),'https://example.com/catalogo.pdf'));
run(`var ocs=[{id:'o1',codigo:'OC-1',fornecedorId:'f1',itens:[{id:'i',descricao:'ACM',unid:'un'}],recebimentos:[{id:'r1',em:'2026-10-01T01:00:00Z',transportadoraId:'t1',itens:[{itemId:'i',qtd:2,unid:'un'}]}]}];var key=chaveFrete('o1','r1');var gastos=[{id:key,ocId:'o1',recebimentoId:'r1',transportadoraId:'t1',dataEntrega:'2026-10-01',custeio:'empresa',valor:125.5}];`);
test('Data ausente não vira 1970',()=>assert.equal(run(`dataEntregaLocal(null)`),''));
test('Entrega às 22h pertence ao dia local',()=>assert.equal(run(`movimentosTransporte(ocs,[])[0].dataEntrega`),'2026-09-30'));
test('Conferência preserva a data original',()=>assert.equal(run(`movimentosTransporte(ocs,gastos)[0].dataEntrega`),'2026-09-30'));
test('Um recebimento e seu frete são uma entrega',()=>assert.equal(run(`movimentosTransporte(ocs,gastos).length`),1));
test('Custo somado uma vez',()=>assert.equal(run(`resumoFretes(movimentosTransporte(ocs,gastos)).gasto`),125.5));
test('Frete ausente fica pendente',()=>assert.equal(run(`resumoFretes(movimentosTransporte(ocs,[])).pendentes`),1));
test('Conteúdo vem dos itens recebidos',()=>assert.equal(run(`movimentosTransporte(ocs,gastos)[0].conteudo`),'2 un ACM'));
test('Gasto não cria pagamento nem altera OC',()=>assert.equal(run(`ocs[0].frete`),undefined));
test('Valor zero conhecido não é pendente',()=>assert.equal(run(`resumoFretes([{custeio:'empresa',valor:0}]).pendentes`),0));
test('Incluso não soma duas vezes',()=>assert.equal(run(`resumoFretes([{custeio:'incluso',valor:100}]).gasto`),0));
test('Valores ausentes, negativos ou inválidos não entram no total',()=>assert.equal(run(`resumoFretes([{custeio:'empresa',valor:null},{custeio:'empresa',valor:-1},{custeio:'empresa',valor:NaN}]).pendentes`),3));
test('Chave determinística de recebimento',()=>assert.equal(run(`key`),chaveRecebimento('o1','r1')));
const db={forn:{f1:{id:'f1'}},mat:{m1:{id:'m1',unidade:'un'}},transp:{t1:{id:'t1'}},oc:{o1:{id:'o1',fornecedorId:'f1',recebimentos:[{id:'r1',em:'2026-10-01T01:00:00Z'}]}}};const ler=async(c,id)=>db[c]?.[id]||null;
const valido={id:chaveRecebimento('o1','r1'),ocId:'o1',recebimentoId:'r1',transportadoraId:'t1',dataEntrega:'2026-10-01',custeio:'empresa',valor:100,conteudo:'ACM'};
await validarRede('frete',valido,null,ler);test('Servidor fixa data do recebimento',()=>assert.equal(valido.dataEntrega,'2026-09-30'));
for(const patch of [{id:'aleatorio'},{transportadoraId:'inexistente'},{valor:-2},{valor:Infinity},{valor:'100'},{recebimentoId:'inexistente'},{custeio:'nao_sei'},{ocId:''}]){await assert.rejects(()=>validarRede('frete',{...valido,...patch},null,ler));n++;}
await assert.rejects(()=>validarRede('frete',{...valido,ocId:'',recebimentoId:'',dataEntrega:'2026-02-30'},null,ler));n++;
await assert.rejects(()=>validarRede('oferta',{fornecedorId:'f1',materialId:'m1',unidade:'m',nomeFornecedor:'Outro'},null,ler));n++;
await assert.rejects(()=>validarRede('oferta',{fornecedorId:'f1',materialId:'m1',unidade:'un',nomeFornecedor:'Outro',catalogoId:'inexistente'},null,ler));n++;
await assert.rejects(()=>validarRede('mat',{nome:'ACM',unidade:'m'},{unidade:'un'},ler));n++;
await assert.rejects(()=>validarRede('proj',{url:'javascript:alert(1)'},null,ler));n++;
await assert.rejects(()=>validarRede('proj',{fornecedorId:'sumiu'},null,ler));n++;
test('Coleções entram no backup central',()=>{for(const c of ['transp','mat','oferta','frete'])assert(c in COLECOES);});
let acesso=stripTypeScriptTypes(readFileSync('supabase/functions/_shared/acesso.ts','utf8')).replace(/^import .*?;$/gm,'').replace(/\bexport /g,'');
const ac=vm.createContext({Deno:{env:{get:()=>''}},createClient:()=>({}),TextEncoder,console});vm.runInContext(acesso,ac);
test('Solicitante não lê despesas nem ofertas privadas',()=>assert.equal(vm.runInContext(`filtrarLeitura({perfil:'obra'},[{_col:'frete',valor:100},{_col:'oferta',nomeFornecedor:'privado'}]).length`,ac),0));
test('Solicitante lê materiais e cobertura para receber',()=>assert.equal(vm.runInContext(`filtrarLeitura({perfil:'obra'},[{_col:'mat'},{_col:'transp'}]).length`,ac),2));
for(const c of ['transp','mat','oferta','frete'])test('Solicitante não grava '+c,()=>assert(vm.runInContext(`motivoRecusa({perfil:'obra'},'${c}',{id:'x'},null)`,ac)));
console.log(`${n} verificações de rede, fretes, catálogos e permissões passaram`);
